### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by niknetniko** [apsun/GoogleImageShell#1]
Thank you for this wonderful program!

I have a question though: would it be possible to use translations? It would be cool if it worked with the system language and uses English as a fallback.

**Comment by apsun** [comment]
I was originally considering this, but you can't embed strings into a .NET assembly (I think) so it would require distributing a DLL file with the program.

Maybe a different option would be to let the user enter the text to display when they install the program? That way they can translate it however they want and everything is still in one file.

**Comment by niknetniko** [comment]
That would be a good solution indeed :)

Op 21 jul. 2016 02:05 schreef "Andrew Sun" notifications@github.com:

**Comment by apsun** [comment]
Added in https://github.com/apsun/GoogleImageShell/commit/0e66d353163c48db23e2100b031e062028c2d3a8

Since the Windows command prompt sucks at handling Unicode (which I imagine would be necessary for localizing the text), I went all-in and rewrote it as a GUI app.

Ironically, this change actually added more strings that need to be localized. Ehh... I imagine nobody looks at the configuration app after installation anyways, so I don't think it's necessary to localize that part :-p

**Comment by niknetniko** [comment]
Thanks a lot :+1:
